//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerSmell
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountAsDate
    {
        public Nullable<decimal> Sum { get; set; }
        public System.DateTime Namee { get; set; }
    }
}
