//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerSmell
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int ID { get; set; }
        public int ID_Type { get; set; }
        public int ID_Client { get; set; }
        public int Amount { get; set; }
        public int ID_Range { get; set; }
        public int ID_Delivery { get; set; }
        public System.DateTime DateOfSale { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Delivery Delivery { get; set; }
        public virtual Range Range { get; set; }
        public virtual Type Type { get; set; }
    }
}
